Repository hannestschofenig/mbedtls, pull requests merged in 2021-05, with the labels that each got.

#251 Key schedule rework: Add documentation
  include/mbedtls/ssl_internal.h
  library/ssl_tls13_keys.c
  library/ssl_tls13_keys.h
Labels: enhancement

#263 Fix client-side behaviour if PSK is offered but rejected by the server
  include/mbedtls/ssl_internal.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_keys.c
  library/ssl_tls13_server.c
Labels: bug

#118 Fix client crash when use early data without psk
  library/ssl_tls13_generic.c
  library/ssl_tls13_keys.c
Labels: needs work
