Repository hannestschofenig/mbedtls, pull requests merged in 2021-01, with the labels that each got.

#100 Add opaque context parameter to MPS I/O callbacks
  include/mbedtls/mps/common.h
  include/mbedtls/mps/layer1.h
  include/mbedtls/mps/transform.h
  library/CMakeLists.txt
  library/Makefile
  library/mps/layer1.c
  library/mps/layer2.c
  library/mps/mps.c
  library/mps/transform.c
  tests/suites/test_suite_mps.function
Labels: enhancement

#105 Add guards to MPS functions only used for tracing
  library/mps/layer2.c
  library/mps/mps.c
Labels: bug

#106 Remove misplaced TLS 1.3 test certificates
  tests/certs/ca.crt
  tests/certs/ca.key
  tests/certs/ca.srl
  tests/certs/server.crt
  tests/certs/server.csr
  tests/certs/server.key
  tests/ssl-opt.sh
Labels: bug

#93 Implement early data status
  include/mbedtls/ssl.h
  include/mbedtls/ssl_internal.h
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  programs/ssl/ssl_client2.c
  tests/ssl-opt.sh
Labels: API extension, enhancement

#123 Move mbedtls_ssl_handshake_key_derivation from ee prepare to sh post
  library/ssl_tls13_client.c
Labels: enhancement, needs work

#129 Improve identifiers and logic around key exchange mode handling
  include/mbedtls/ssl.h
  include/mbedtls/ssl_internal.h
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
  programs/ssl/ssl_client2.c
  programs/ssl/ssl_server2.c
  tests/ssl-opt.sh
Labels: bug, enhancement

#132 Remove duplicated code for calculation of PSK binders
  include/mbedtls/ssl_internal.h
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
Labels: enhancement

#78 Send pending alert after ssl_server_hello_process
  library/ssl_tls13_client.c
Labels: bug, needs work

#137 Improve structure and reduce code-duplication around HS transcripts and PSK binders
  include/mbedtls/ssl_internal.h
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
Labels: bug

#107 Introduce MPS and use for CH+SH writing
  include/mbedtls/config.h
  include/mbedtls/mps/common.h
  include/mbedtls/mps/layer1.h
  include/mbedtls/mps/mps.h
  include/mbedtls/ssl.h
  include/mbedtls/ssl_internal.h
  library/mps/layer1.c
  library/ssl_msg.c
  library/ssl_tls.c
  library/ssl_tls13_client.c
  library/ssl_tls13_generic.c
  library/ssl_tls13_server.c
Labels: enhancement

#92 Add rsa_pss_rsae_sha256 to supported sigalgos list
  include/mbedtls/ssl.h
  library/ssl_tls.c
  library/ssl_tls13_generic.c
  programs/ssl/ssl_client2.c
  tests/scripts/all.sh
  tests/ssl-opt.sh
Labels: API extension, Needs design discussion, enhancement, needs work
